{
 "title": "Vélo'v Lyon - Real-Time Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Carte Interactive des Stations en Alerte",
   "type": "geomap",
   "description": "Carte des Alertes Vélo'v Lyon",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "velov_db",
     "rawSql": "SELECT \r\n    lat,\r\n    lng,\r\n    name,\r\n    alert_type,\r\n    bikes_available,\r\n    docks_available\r\nFROM velov_station_alerts;"
    }
   ]
  },
  {
   "title": "Tableau des Dernières Alertes en Direct",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "velov_db",
     "rawSql": "SELECT \r\n    (processed_at) AS \"Horodatage\",\r\n    name AS \"Station\",\r\n    commune AS \"Commune\",\r\n    alert_type AS \"Type d'Alerte\",\r\n    alert_message AS \"Message\",\r\n    bikes_available AS \"Vélos Dispo\"\r\nFROM velov_station_alerts\r\nORDER BY processed_at DESC\r\nLIMIT 50;"
    }
   ]
  },
  {
   "title": "Statistique des Stations Vides",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "velov_db" },
    {
     "dataset": "velov_db",
     "rawSql": "SELECT COUNT(DISTINCT station_number) \r\nFROM velov_station_alerts \r\nWHERE alert_type = 'EMPTY_STATION';"
    }
   ]
  }
 ]
}